### ISSUE TITLE
comparison to sony webpage instructions

### ISSUE THREAD

**Issue by jamuir** [sonyxperiadev/repo_update#1]
@jerpelea:  thank-you for creating this script!

I notice that the git operations applied here differ from those posted on the Sony opendevices web page:

https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/

(diff screenshot attached below)
 
My guess is that the operations here are meant to supersede the information on the webpage.

Is that correct?

![diff](https://user-images.githubusercontent.com/5332385/30077168-fe355256-9248-11e7-8c9d-87058f01b25d.jpg)

**Comment by jerpelea** [comment]
The information from the webpage is for 3 Android 7 build guides for each kernel version while the information from here is unified and should be used for all 3 build guides.
The n-mr build guides don't use the new script and we will update the build guides soon, to reflect the changes!

**Comment by jamuir** [comment]
Thanks for your reply.

I see the build guides have been updated on the Sony webpages now.  All the 7.1 builds use the new script, and so does the 8.0 build. :+1:
