### ISSUE TITLE
srcipt adds merge conflicts for n-mr1

### ISSUE THREAD

**Issue by TitanNano** [sonyxperiadev/repo_update#17]
The `n-mr1` branch version of this script introduces quite a few merge conflicts in the source of AOSP 7.1. Would it be possible for you to fix this?

**Comment by jerpelea** [comment]
I just synced the n-mr1 branch and there is no conflict
please follow the guide and pick the correct branch

**Comment by jerpelea** [comment]
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/
