### ISSUE TITLE
AOSP 8.0.0_r11 build error

### ISSUE THREAD

**Issue by vladimir-zahradnik** [sonyxperiadev/repo_update#2]
Hello,
I'm trying to build latest AOSP image with tag android-8.0.0_r11 for Xperia X.
I applied your repo_update script from master branch and build fails with following error:

,--end-group out/target/product/generic/obj/lib/crtend_android.o"
system/core/healthd/healthd_mode_charger.cpp:671: error: undefined reference to 'healthd_board_mode_charger_set_backlight(bool)'
system/core/healthd/healthd_mode_charger.cpp:696: error: undefined reference to 'healthd_board_mode_charger_battery_update(android::BatteryProperties*)'
system/core/healthd/healthd_mode_charger.cpp:484: error: undefined reference to 'healthd_board_mode_charger_set_backlight(bool)'
system/core/healthd/healthd_mode_charger.cpp:494: error: undefined reference to 'healthd_board_mode_charger_set_backlight(bool)'
system/core/healthd/healthd_mode_charger.cpp:531: error: undefined reference to 'healthd_board_mode_charger_set_backlight(bool)'
system/core/healthd/healthd_mode_charger.cpp:412: error: undefined reference to 'healthd_board_mode_charger_draw_battery(android::BatteryProperties*)'
system/core/healthd/healthd_mode_charger.cpp:861: error: undefined reference to 'healthd_board_mode_charger_init()'

I tracked this issue to following lines in your script:
cd ../../../system/core
git fetch http://android.googlesource.com/platform/system/core refs/changes/37/469437/1 && git cherry-pick FETCH_HEAD

If I don't apply above commit, my build continues OK. Please take a look at it.

Thanks!

**Comment by vladimir-zahradnik** [comment]
Hello,
I built AOSP again exactly per your instructions and this time build went fine. Issue can be closed.

Thanks!

**Comment by DarthBenro008** [comment]
Hey , i am facing the same issue may i know what did you do to fix this issue? did you sync the repo again? or u started from scratch again?

**Comment by jerpelea** [comment]
we are moving the vendors to a nre vendor image and untill monday it is not possible to build and boot android

**Comment by vladimir-zahradnik** [comment]
@DarthBenro008 I built my own AOSP manifest and I tried to include in it all repos defined in Xperia local manifest files. This is when I hit mentioned error. To elliminate all issues with my config I followed Xperia build instructions exactly and I made clean build, e.g. unmodified AOSP build from scratch. This time build succeded, hence I closed this issue.

Now I'm able to boot the image, but I noticed that adb logcat prints lots of text, which makes debugging very problematic. Also sometimes I face reboots. However I didn't check latest code, maybe it's already fixed.

**Comment by jerpelea** [comment]
all the needed patchs needed to build Android have been added to a script (repo_update.sh)
This script is mentioned in the build guide and can be found in the root of your android folder after the first repo sync.
please note that after this weekend's changed, for a succesfull boot you will need a new vendor release 
that will be released Monday.(the old vendor.zip containing blobs is deprecated !)
