### ISSUE TITLE
confilct when fetch and cherry-pick  refs/changes/37/469437/1

### ISSUE THREAD

**Issue by GggXp** [sonyxperiadev/repo_update#34]
confilct when fetch and cherry-pick  refs/changes/37/469437/1
i am building android-8.1.0_r20 for G8142

**Comment by jerpelea** [comment]
cd system/core
git reset --hard 
cd ../..
repo_update.sh 

should fix your local issue

**Comment by GggXp** [comment]
![image](https://user-images.githubusercontent.com/5029513/38500888-3c0dd932-3c3e-11e8-9292-e688195b1f03.png)

来自 https://android.googlesource.com/platform/system/core
 * branch                  refs/changes/41/501741/2 -> FETCH_HEAD
[分离头指针 1255a73fe8] Allow firmware loading from ODM partition
 Author: Alin Jerpelea <alin.jerpelea@sonymobile.com>
 Date: Wed Oct 4 06:44:57 2017 +0200
 1 file changed, 2 insertions(+), 2 deletions(-)
fatal: bad object 1d540dd0f44c1c7d40878f6a7bb447e85e6207ad
来自 https://android.googlesource.com/platform/system/core
 * branch                  refs/changes/37/469437/1 -> FETCH_HEAD
error: 不能应用 3ad34b520b... healthd: charger: Add board overrides in mode_charger
提示：冲突解决完毕后，用 'git add <路径>' 或 'git rm <路径>'
提示：对修正后的文件做标记，然后用 'git commit' 提交
Resolved 'healthd/healthd_mode_charger.cpp' using previous resolution.
sorry for Chinese display

**Comment by YumeMichi** [comment]
Did you forget this? https://github.com/sonyxperiadev/repo_update/blob/master/repo_update.sh#L79

**Comment by YumeMichi** [comment]
In your terminal:
```
fatal: bad object 1d540dd0f44c1c7d40878f6a7bb447e85e6207ad
```

**Comment by GggXp** [comment]
no，i never changed any single letter in the script, I just follow the build instruction and it goes wrong
